---
apiVersion: v2
dependencies:
  - name: redis-exporter
    version: v2.0.7
name: forms-flow-analytics
tags: forms-flow-analytics
version: v4.0.0
icon: "https://raw.githubusercontent.com/AOT-Technologies/forms-flow-ai/develop/.images/logo.png"
