---
apiVersion: v2
name: forms-flow-ai
dependencies:
  - name: postgresql-ha
    condition: postgresql-ha.enabled 
    repository: https://charts.bitnami.com/bitnami
    version: 13.4.5
  - name: mongodb
    condition: mongodb.enabled 
    repository: https://charts.bitnami.com/bitnami
    version: 13.6.3
  - name: redis-exporter
    version: v3.0.0
version: v6.0.0
icon: "https://raw.githubusercontent.com/AOT-Technologies/forms-flow-ai/develop/.images/logo.png"